### PR TITLE
Support for React 17 in Peer Dependencies

### PR DESCRIPTION
**Pull request by mantovanig**
## Description
This PR adds support for React 17 in the peerDependencies section of the package.json. This update ensures compatibility and resolves peer dependency warnings for projects using React 17.

## Changes Made
Updated package.json to include React 17 in peerDependencies.

## Testing
Ran all automated tests locally.
Verified successful build of the library.

### CODE REVIEW

**Comment by viclafouch** [comment]
Hello !

I don't know if the source code is compatible avec React 17. I didn't run any test.

**Comment by enoh-barbu** [comment]
@viclafouch such a pitty, my project runs on v17 and I will not upgrate to v18 very soon...

**Comment by enoh-barbu** [comment]
what do you mean? you will or will not? which versions? R17 / R18 / R19?

**Comment by viclafouch** [comment]
Only R18 & 19.

**Pull request closed without merging**
