### PR TITLE
fix: maintain cursor position after a change

### PR DESCRIPTION
**Pull request by sayedi-hassan**
This pull request resolves two cursor positioning issues in the MUI Tel Input component:

- Prevents the cursor from jumping to the end of existing text when clicked. Users can now start editing from the clicked location.
- Maintains cursor position after making changes to the input.

Linked Issue: [#3](https://github.com/viclafouch/mui-tel-input/issues/5)

### CODE REVIEW

**Comment by viclafouch** [comment]
Hey @sayedi-hassan !

There is an issue that I'm trying to fix, maybe you could help, even if I already merged the PR.

Repro : 
* Select all
* Clear
* Write 32

The result is : +23
Expected behavior : +32

BTW, a test is faliing, that is correct

```ts
test('should change flag if we change the calling code', async () => {
    render(<MuiTelWrapper defaultCountry="FR" />)
    await userEvent.clear(getInputElement())
    const { result } = await typeInInputElement('32')
    expect(result).toBe('+32') // => Fail, it's +23
    expectButtonIsFlagOf('BE')
  })

```

https://github.com/viclafouch/mui-tel-input/assets/23353836/0e9a96ff-8660-4531-96d2-6e905b5ddebe

**Comment by viclafouch** [comment]
Hey @sayedi-hassan !

There is an issue that I'm trying to fix, maybe you could help, even if I already merged the PR.

Repro : 
* Select all
* Clear
* Write 32

The result is : +23
Expected behavior : +32

BTW, a test is faliing, that is correct

```ts
test('should change flag if we change the calling code', async () => {
    render(<MuiTelWrapper defaultCountry="FR" />)
    await userEvent.clear(getInputElement())
    const { result } = await typeInInputElement('32')
    expect(result).toBe('+32') // => Fail, it's +23
    expectButtonIsFlagOf('BE')
  })

```

https://github.com/viclafouch/mui-tel-input/assets/23353836/0e9a96ff-8660-4531-96d2-6e905b5ddebe

**Comment by JayWelsh** [comment]
@sayedi-hassan have you maybe had a chance to review the failure case of this adjustment?

**Comment by akyllo34** [comment]
Hi all, Ive had a similar issue in my code base. While positioning the caret manually can help i found the best solution to be using a wrapper around the component in question that allows the value to be set synchronously and asynchronously at the same time. https://gist.github.com/mjsarfatti/6e1261f0be5f3c9eef5da1cda7bd3ffe

**Pull request merged**
